name: asq3-eyfs
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - libffi=3.4.4
  - narwhals=2.7.0
  - ncurses=6.4
  - openssl=3.0.19
  - pip=24.2
  - python=3.11.11
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - alembic==1.16.4
      - anyio==4.7.0
      - appnope==0.1.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - attrs==24.3.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blinker==1.9.0
      - bokeh==2.4.3
      - bottleneck==1.4.2
      - category-encoders==2.7.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - choreographer==1.0.9
      - click==8.2.1
      - cloudpickle==3.1.0
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.1.2
      - dash==3.2.0
      - dask==2.30.0
      - dataprep==0.4.1
      - debugpy==1.8.11
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - entrypoints==0.4
      - executing==0.8.3
      - fastjsonschema==2.21.1
      - flask==3.1.1
      - flask-cors==3.0.10
      - fonttools==4.55.3
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - future==1.0.0
      - hyperopt==0.2.7
      - idna==3.10
      - imbalanced-learn==0.13.0
      - importlib-metadata==8.7.0
      - ipykernel==6.29.5
      - ipyplot==1.1.2
      - ipython==8.31.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.8.5
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.3.2
      - jsonpath-ng==1.7.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==7.4.9
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-server==2.13.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==1.1.11
      - kaleido==1.0.0
      - kiwisolver==1.4.8
      - levenshtein==0.12.0
      - lightgbm==4.6.0
      - llvmlite==0.44.0
      - locket==1.0.0
      - logistro==1.1.0
      - mako==1.3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - metaphone==0.6
      - mistune==0.8.4
      - multidict==6.1.0
      - nbclassic==1.1.0
      - nbclient==0.5.13
      - nbconvert==6.4.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - nltk==3.6.3
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.26.4
      - optuna==4.4.0
      - optuna-integration==4.4.0
      - orjson==3.11.1
      - overrides==7.7.0
      - packaging==24.2
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - plotly-resampler==0.10.0
      - ply==3.11
      - pmdarima==2.0.4
      - probableparsing==0.0.1
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - propcache==0.2.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py4j==0.10.9.9
      - pyaml==25.7.0
      - pyarrow==21.0.0
      - pycaret==3.3.2
      - pycparser==2.23
      - pydantic==1.10.19
      - pygments==2.18.0
      - pyod==2.0.5
      - pyparsing==3.2.1
      - python-crfsuite==0.9.11
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - python-stdnum==1.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2020.11.13
      - requests==2.32.4
      - retrying==1.4.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.2.0
      - rpds-py==0.22.3
      - rpy2==3.6.4
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
      - schemdraw==0.15
      - scikit-base==0.7.8
      - scikit-learn==1.4.2
      - scikit-optimize==0.10.2
      - scikit-plot==0.3.7
      - scipy==1.11.4
      - seaborn==0.13.2
      - send2trash==1.8.3
      - shortuuid==1.0.13
      - simplejson==3.20.1
      - six==1.17.0
      - sklearn-compat==0.1.3
      - sktime==0.26.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.42
      - stack-data==0.5.1
      - statsmodels==0.14.5
      - tabulate==0.9.0
      - tbats==1.1.3
      - tenacity==9.1.2
      - terminado==0.18.1
      - testpath==0.6.0
      - threadpoolctl==3.6.0
      - toolz==1.0.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - tsdownsample==0.1.4.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzlocal==5.3.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - usaddress==0.5.11
      - varname==0.8.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==3.6.10
      - wordcloud==1.9.4
      - wurlitzer==3.1.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - yellowbrick==1.5
      - zipp==3.23.0
